#!/bin/zsh

bat_num=${BLOCK_INSTANCE:-1}
dir=/sys/class/power_supply/BAT$bat_num

[ -d $dir ] || exit 0

capacity=$(cat "${dir}/capacity")
microwatts=$(cat "${dir}/power_now")
state=$(cat "${dir}/status")

echo "$state $capacity $microwatts" | awk -f <(cat <<EOF
{
  state = \$1;
  capacity = \$2;
  microwatts = \$3;
}
END {
  if (state == "Charging") {
    icon = "";
  }
  else {
    if (state == "Full" || capacity > 80) {
      icon = "";
    }
    else if (capacity > 60) {
      icon = "";
    }
    else if (capacity > 40) {
      icon = "";
    }
    else if (capacity > 20) {
      icon = "";
    }
    else {
      icon = "";
    }
  }

  if (capacity <= 10) {
    exit_code = 33;
  }
  if (capacity <= 20) {
    color = "#e74c3c";
  }
  else if (capacity <= 35) {
    color = "#f1c40f";
  }

  full_text = sprintf("%s %d%%", icon, capacity);
  if (microwatts > 0) {
    full_text = sprintf("%s %.1fW", full_text, microwatts / 1e6);
  }

  printf("%s\n", full_text);
  printf("%d%%\n", capacity);
  if (color) {
    print color;
  }
  exit exit_code;
}
EOF
    )

case $BLOCK_BUTTON in
  1) gnome-power-statistics & ;;
esac
