#!/bin/zsh

set -euo pipefail

read cpu a b c previdle rest < /proc/stat
prevtotal=$((a + b + c + previdle))

sleep 0.5 &

root=/sys/devices/system/cpu
cpus=$(ls -1d $root/cpu[0-9]*/ |wc -l)
tot=$(cat $root/cpu[0-9]*/cpufreq/scaling_cur_freq | paste -sd+ | bc)
freq=$(printf '%0.01f' $(echo "2 k $tot $cpus 1000000 * / p" | dc))

wait

read cpu a b c idle rest < /proc/stat
total=$((a + b + c + idle))
usage=$((100 * (total - prevtotal - (idle - previdle)) / (total - prevtotal)))

echo "${usage}% ${freq}GHz"
echo "${usage}% ${freq}GHz"

mouse_button=${BLOCK_BUTTON:-}
case "$mouse_button" in
  1) gnome-system-monitor -p & ;;
esac
