#!/usr/bin/env node

var http = require('http');
var util = require('util');

var stdout = process.stdout;
var team = process.env.BLOCK_INSTANCE || process.argv[2];

var now = new Date();
var year = now.getFullYear();
var month = now.getMonth() + 1;
var day = now.getDate();

var uriPath = util.format(
  '/components/game/mlb/year_%d/month_%s/day_%s/master_scoreboard.json',
  year, pad02(month), pad02(day));

http.get({host: 'gd2.mlb.com', path: uriPath}, handleResponse);

function handleResponse(response) {
  var body = '';
  response
    .on('data', function(data) {
      body += data;
    })
    .on('end', function() {
      handleResponseBody(body);
    });
}

function handleResponseBody(body) {
  var json = JSON.parse(body);

  var game = json.data.games.game;
  if (!!game) {
    game = game.reverse().filter(isTeamGame)[0];
  }

  if (!!game) {
    var home = game.home_name_abbrev;
    var away = game.away_name_abbrev;
    var status = game.status.status;
    var ls = game.linescore;
    var summary;
    var color;

    if ('Preview' === status || 'Pre-Game' === status) {
      summary = util.format(
        '%s @ %s %s%s',
        away, home,
        (team === home ? game.home_time : game.away_time),
        (team === home ? game.home_ampm : game.away_ampm));
    }
    else {
      summary = util.format(
        '%s %d @ %s %d',
        away, (ls ? ls.r.away : 0),
        home, (ls ? ls.r.home : 0));

      if ('In Progress' === status) {
        var inningState = game.status.inning_state;
        inningState = ('Top' === inningState ? '' : '');
        summary = util.format(
          '%s %s %d',
          summary, inningState, game.status.inning);
      }
      else if ('Final' === status || 'Game Over' === status) {
        color = (
          ((team === home && ls.r.home > ls.r.away) ||
           (team === away && ls.r.away > ls.r.home)) ?
            '#27ae60' : '#c0392b');
      }
      else {
        summary = util.format('%s %s', summary, status);
      }
    }

    stdout.write(util.format('%s\n', summary));
    stdout.write(util.format('%s\n', summary));
    if (!!color) {
      stdout.write(util.format('%s\n', color));
    }
  }
}

function isTeamGame(game) {
  return (game.home_name_abbrev === team || game.away_name_abbrev === team);
}

function pad02(n) {
  return util.format('00%d', n).slice(-2);
}
