#!/bin/sh

mute=$(pactl list sinks |grep 'Mute: yes')
if [ -n "$mute" ]; then
  vol="M̶"
  color='#e74c3c'
else
  vol=$(pactl list sinks |grep '^[[:space:]]Volume:' |tail -n1 |awk '{print$5}' |sed 's#%$##')
  if [ $vol -lt 20 ]; then
    color='#e74c3c'
  elif [ $vol -ge 80 ]; then
    color='#27ae60'
  else
    color='#f1c40f'
  fi
  vol=$vol%
fi

echo $vol
echo $vol
echo $color

case $BLOCK_BUTTON in
  1)
    pavucontrol &
    ;;
esac
