#!/bin/zsh

set -euo pipefail

mute=$(pactl list sinks |grep 'Mute: yes' || echo '')
if [ -n "$mute" ]; then
  vol="M̶"
  color='#e74c3c'
else
  vol=$(pactl list sinks |grep '^[[:space:]]Volume:' |tail -n1 |awk '{print$5}' |sed 's#%$##')
  if [ $vol -lt 33 ]; then
    color='#e74c3c'
  elif [ $vol -ge 66 ]; then
    color='#27ae60'
  else
    color='#f1c40f'
  fi
  vol=$vol%
fi

echo $vol
echo $vol
echo $color

mouse_button=${BLOCK_BUTTON:-}
case "$mouse_button" in
  1) pavucontrol & ;;
esac
