#!/bin/zsh

set -euo pipefail

sink_name=$(pactl list short sinks |grep -v SUSPENDED |tail -n1 |awk '{print$2}')
mute=$(pactl list sinks |awk "{if(\$1~/^Name:\$/){n=\$2}if(n==\"$sink_name\"&&\$1~/^Mute:\$/){print\$2}}")
if [ _"$mute" = "_yes" ]; then
  vol="M̶"
  color='#e74c3c'
else
  vol=$(pactl list sinks |awk "{if(\$1~/^Name:\$/){n=\$2}if(n==\"$sink_name\"&&\$1~/^Volume:\$/){print\$5}}" |sed 's#%$##')
  if [ $vol -lt 33 ]; then
    color='#e74c3c'
  elif [ $vol -ge 66 ]; then
    color='#27ae60'
  else
    color='#f1c40f'
  fi
  vol=$vol%
fi

echo $vol
echo $vol
echo $color

mouse_button=${BLOCK_BUTTON:-}
case "$mouse_button" in
  1) pavucontrol & ;;
esac
