#!/bin/zsh

set -euo pipefail

[ "$BLOCK_INSTANCE" -a "$BLOCK_INSTANCE" != "NONE" ] || exit 0

iw dev "$BLOCK_INSTANCE" link | awk -f <(cat <<'EOF'
{
  if ($1 == "SSID:") {
    ssid = $2;
  }
  else if ($1 == "signal:") {
    signal = $2;
    if ($2 > -50) {
      q = "⣿";
    }
    else if ($2 > -60) {
      q = "⣶";
    }
    else if ($2 > -70) {
      q = "⣤";
      color = "#f1c40f";
    }
    else {
      q = "⣀";
      color = "#e74c3c";
    }
  }
}
END {
  if (ssid) {
    printf("%s %d %s\n", q, signal, ssid);
    printf("%d\n", signal);
    if (color) {
      print color;
    }
  }
}
EOF
                                )

case $BLOCK_BUTTON in
  1) gnome-nettool & ;;
esac
