(global-set-key (kbd "C--") 'spacemacs/scale-down-font)
(global-set-key (kbd "C-=") 'spacemacs/scale-up-font)
(global-set-key (kbd "C-x C-f") 'counsel-git)
(global-set-key (kbd "C-x M-f") 'find-file)
(global-set-key (kbd "C-x b") 'ibuffer)
