(global-set-key (kbd "C--") 'spacemacs/scale-down-font)
(global-set-key (kbd "C-=") 'spacemacs/scale-up-font)
(global-set-key (kbd "C-x C-f") 'counsel-projectile-find-file)
(global-set-key (kbd "C-x M-b") 'switch-to-buffer)
(global-set-key (kbd "C-x M-f") 'find-file)
(global-set-key (kbd "C-x b") 'counsel-projectile-switch-to-buffer)
(global-set-key (kbd "\C-r") 'swiper)
