(global-set-key (kbd "C--") 'spacemacs/scale-down-font)
(global-set-key (kbd "C-=") 'spacemacs/scale-up-font)
(global-set-key (kbd "C-x C-f") 'counsel-projectile)
(global-set-key (kbd "C-x M-b") 'ivy-switch-buffer)
(global-set-key (kbd "C-x M-f") 'counsel-find-file)
(global-set-key (kbd "C-x b") 'projectile-switch-to-buffer)
(global-set-key (kbd "\C-r") 'swiper)
(global-set-key (kbd "M-g c") 'avy-goto-char-timer)
(global-set-key (kbd "M-g g") 'avy-goto-line)
(global-set-key (kbd "M-g w") 'avy-goto-word-1)
(global-set-key (kbd "M-p") 'ace-window)
